### ISSUE TITLE
Update the peer Dependencies to the latest versions

### ISSUE THREAD

**Issue by mducptit** [huy97/csrf#11]
The peer dependencies used in the package are older versions. It will be good to update to the newest version so that there will be no conflict withe the versions.

@nestjs/common@"^9.4.2" =>  @nestjs/common@"^10.1.2"

Logs:
```
npm ERR! Found: @nestjs/common@10.1.2
npm ERR! node_modules/@nestjs/common
npm ERR!   @nestjs/common@"^10.1.2" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @nestjs/common@"^9.4.2" from ncsrf@1.0.10
npm ERR! node_modules/ncsrf
npm ERR!   ncsrf@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

**Comment by xbisa** [comment]
I have same issue after I upgraded from Nest version 9 to 10.

`
Found: @nestjs/common@10.2.1
npm ERR! node_modules/@nestjs/common
npm ERR!   @nestjs/common@"^10.2.1" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer @nestjs/common@"^9.4.2" from ncsrf@1.0.10
npm ERR! node_modules/ncsrf
npm ERR!   ncsrf@"1.0.10" from the root project

`

**Comment by huy97** [comment]
I will upgrade it as soon as, thanks for using.

**Comment by dev-manhnt** [comment]
Please use ^[v1.0.10](https://github.com/huy97/csrf/commit/6a38e6469aca0a5140e2f4490255fed1a5445231) or `yarn` instead

**Comment by rslowinski** [comment]
any updates? :)

**Comment by simonbarker** [comment]
Any updates on this? At the moment I can't update to NestJS10 due to a mass of peer dependency conflicts

**Comment by dvantage** [comment]
UP

**Comment by huy97** [comment]
Thank you for reporting the issue and for using this library. I have released an update in the latest version to fix the bug. Please check it out
