### ISSUE TITLE
@Csrf() decorator always throws 403 exception

### ISSUE THREAD

**Issue by viethai-tr** [huy97/csrf#12]
Hello, I'm having an issue with `@Csrf()` decoration.
It always throws a 403 exception even when there is a `x-csrf-token` in the request header (the token I received in the response header with `res.csrfToken()`).

![image](https://github.com/huy97/csrf/assets/56261531/ece7ea51-a88a-4661-a84c-d341e58feec7)

I already had `cookieParser` and `nestCsrf` in my `main.ts`.
![image](https://github.com/huy97/csrf/assets/56261531/b61f2d3a-4451-42e8-9e5d-7e849625201a)

**Comment by huy97** [comment]
Thank you for this issue. Please check the following points:

- The library uses a cookie to store the secret key, as shown in the image below, so the cookie needs to be attached to the headers when sending requests.

![image](https://github.com/huy97/csrf/assets/30153437/6536f098-3fbe-408c-b0f9-b18f5b59f881)

- Make sure you have enabled withCredentials = true to automatically attach cookies when using libraries like axios.

Hope the above points will solve the issue you are facing. Thanks
