### ISSUE TITLE
update the peer Dependencies to the latest versions 

### ISSUE THREAD

**Issue by isurumaldeniya** [huy97/csrf#4]
The peer dependencies used in the package are older versions. It will be good to update to the newest version so that there will be no conflict withe the versions. 

"rxjs": "^6.6.3"  => "rxjs": "^7.5.5",
"@nestjs/common": "^7.6.1", => "@nestjs/common": "^8.4.4",

**Comment by huy97** [comment]
Updated on [3bf302](https://github.com/huy97/csrf/commit/3bf302dd90b95e428723c9dceddec34d5742c752)
